ik_node:
  ros__parameters:
    a: 0.05
    b: 0.10
    c: 0.10

    xl: [0.15, 0.15, -0.15, -0.15]
    yl: [0.10, -0.10, 0.10, -0.10]
    zl: [0.0, 0.0, 0.0, 0.0]

    side_sign: [1.0, -1.0, 1.0, -1.0]